version: '3'

services:
  db:
    image: 'postgres:12.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    volumes:
      - .:/qcxchallenge
      - gems:/gems
    depends_on:
      - db

volumes:
  postgres:
  gems:
